### ISSUE TITLE
Failed to load the atom-perforce package

### ISSUE THREAD

**Issue by narendraumate** [mattsawyer77/atom-perforce#16]
[Enter steps to reproduce below:]
1. Build atom from source
2. Linked fork

**Atom Version**: 1.0.1-cb81554
**System**: Mac OS X 10.10.3
**Thrown From**: [atom-perforce](https://github.com/mattsawyer77/atom-perforce) package, v1.2.1
### Stack Trace

Failed to load the atom-perforce package

```
At Cannot find module 'q'

Error: Cannot find module 'q'
  at Module._resolveFilename (module.js:328:15)
  at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
  at Function.Module._load (module.js:270:25)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/Users/ardneran/Documents/Projects/GitHub/atom-perforce/lib/environment.js:4:9)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/babel.js:162:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/Users/ardneran/Documents/Projects/GitHub/atom-perforce/main.js:4:19)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/babel.js:162:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:709:34)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:188:28
  at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:165:15)
  at Package.module.exports.Package.load (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:179:12)
  at PackageManager.module.exports.PackageManager.loadPackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:372:14)
  at PackageManager.module.exports.PackageManager.loadPackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:336:14)
  at Atom.module.exports.Atom.startEditorWindow (/Applications/Atom.app/Contents/Resources/app.asar/src/atom.js:638:21)
  at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-bootstrap.js:12:8)
  at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-bootstrap.js:23:4)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/babel.js:162:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at setupWindow (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:96:23)
  at window.onload (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:36:7)

```
### Commands

```
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-perforce, v1.2.1

# Dev
No dev packages
```

**Comment by mattsawyer77** [comment]
@ardneran this is odd. I don't know of any reason for this. Would you mind quitting the Atom app and trying the following:

```
apm uninstall --hard atom-perforce
apm install atom-perforce
```

then please tell me the output and whether you can use the package in Atom?

**Comment by narendraumate** [comment]
Thank you for the prompt response @mattsawyer77. This helped me after I gave your method a try https://atom.io/docs/v0.80.0/contributing. I had to run the following commands inside my fork.

cd atom-perforce
apm link --dev
apm install
apm update
atom -d
