### ISSUE TITLE
Failed to activate the atom-perforce package

### ISSUE THREAD

**Issue by unional** [mattsawyer77/atom-perforce#32]
[Enter steps to reproduce below:]
1. enable atom-perforce at a folder that is not under p4

**Atom Version**: 1.1.0
**System**: Microsoft Windows Server 2012 R2 Standard
**Thrown From**: [atom-perforce](https://github.com/mattsawyer77/atom-perforce) package, v1.6.0
### Stack Trace

Failed to activate the atom-perforce package

```
At Cannot read property 'reduce' of undefined

TypeError: Cannot read property 'reduce' of undefined
  at Object.extractVarsFromEnvironment (C:\Users\hwong\.atom\packages\atom-perforce\lib\environment.js:68:27)
  at Object.setupEnvironment (C:\Users\hwong\.atom\packages\atom-perforce\lib\atom-perforce.js:127:40)
  at execP4Command (C:\Users\hwong\.atom\packages\atom-perforce\lib\atom-perforce.js:27:64)
  at Object.getChanges (C:\Users\hwong\.atom\packages\atom-perforce\lib\atom-perforce.js:432:13)
  at C:\Users\hwong\.atom\packages\atom-perforce\main.js:93:26
  at Workspace.module.exports.Workspace.observeTextEditors (C:\Users\hwong\AppData\Local\atom\app-1.1.0\resources\app.asar\src\workspace.js:267:9)
  at setupObservers (C:\Users\hwong\.atom\packages\atom-perforce\main.js:67:34)
  at Object.activate (C:\Users\hwong\.atom\packages\atom-perforce\main.js:185:17)
  at Package.module.exports.Package.activateNow (C:\Users\hwong\AppData\Local\atom\app-1.1.0\resources\app.asar\src\package.js:232:19)
  at C:\Users\hwong\AppData\Local\atom\app-1.1.0\resources\app.asar\src\package.js:212:32
  at Package.module.exports.Package.measure (C:\Users\hwong\AppData\Local\atom\app-1.1.0\resources\app.asar\src\package.js:153:15)
  at C:\Users\hwong\AppData\Local\atom\app-1.1.0\resources\app.asar\src\package.js:205:26
  at Package.module.exports.Package.activate (C:\Users\hwong\AppData\Local\atom\app-1.1.0\resources\app.asar\src\package.js:201:34)
  at PackageManager.module.exports.PackageManager.activatePackage (C:\Users\hwong\AppData\Local\atom\app-1.1.0\resources\app.asar\src\package-manager.js:474:21)
  at C:\Users\hwong\AppData\Local\atom\app-1.1.0\resources\app.asar\src\package-manager.js:310:19
  at C:\Users\hwong\AppData\Local\atom\app-1.1.0\resources\app.asar\src\config.js:568:20
  at Emitter.module.exports.Emitter.emit (C:\Users\hwong\AppData\Local\atom\app-1.1.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:86:11)
  at Config.module.exports.Config.emitChangeEvent (C:\Users\hwong\AppData\Local\atom\app-1.1.0\resources\app.asar\src\config.js:753:29)
  at Config.module.exports.Config.setRawValue (C:\Users\hwong\AppData\Local\atom\app-1.1.0\resources\app.asar\src\config.js:545:19)
  at Config.module.exports.Config.set (C:\Users\hwong\AppData\Local\atom\app-1.1.0\resources\app.asar\src\config.js:215:14)
  at Config.module.exports.Config.removeAtKeyPath (C:\Users\hwong\AppData\Local\atom\app-1.1.0\resources\app.asar\src\config.js:332:12)
  at Package.module.exports.Package.enable (C:\Users\hwong\AppData\Local\atom\app-1.1.0\resources\app.asar\src\package.js:138:26)
  at PackageManager.module.exports.PackageManager.enablePackage (C:\Users\hwong\AppData\Local\atom\app-1.1.0\resources\app.asar\src\package-manager.js:139:14)
  at HTMLButtonElement.<anonymous> (C:\Users\hwong\AppData\Local\atom\app-1.1.0\resources\app.asar\node_modules\settings-view\lib\package-card.js:314:27)
  at HTMLButtonElement.jQuery.event.dispatch (C:\Users\hwong\AppData\Local\atom\app-1.1.0\resources\app.asar\node_modules\jquery\dist\jquery.js:4435:9)
  at HTMLButtonElement.elemData.handle (C:\Users\hwong\AppData\Local\atom\app-1.1.0\resources\app.asar\node_modules\jquery\dist\jquery.js:4121:28)

```
### Commands

```
     -1:43 settings-view:open (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "packagesWithKeymapsDisabled": [
      "preview-plus"
    ],
    "disabledPackages": [
      "preview-plus",
      "atom-html-preview",
      "atom-ternjs",
      "atom-trello",
      "browser-plus",
      "compare-files",
      "emmet",
      "git-plus",
      "minimap-find-and-replace",
      ".bin",
      "linter-csslint",
      "linter-eslint",
      "navigate",
      "php-server",
      "pigments",
      "autosave",
      "atom-terminal"
    ],
    "themes": [
      "atom-material-ui",
      "atom-material-syntax"
    ]
  },
  "atom-perforce": {
    "autoAdd": true,
    "autoEdit": true,
    "autoRevert": true
  }
}
```
### Installed Packages

``` coffee
# User
atom-material-syntax, v0.2.4
atom-material-ui, v0.7.1
atom-perforce, v1.6.0
atom-typescript, v7.7.2
auto-indent, v0.5.0
docblockr, v0.7.3
file-icons, v1.6.11
highlight-selected, v0.10.1
linter, v1.10.0
linter-tslint, v0.4.2
minimap, v4.16.0
mocha, v0.0.7
project-manager, v2.6.5

# Dev
No dev packages
```

**Comment by mattsawyer77** [comment]
just published a patch with 1.6.1, please let me know if that doesn't fix the problem as I don't have a windows environment setup to test this with.

**Comment by unional** [comment]
That fixed the problem. Great speed! :)

Another one coming. :)

**Comment by yordis** [comment]
@mattsawyer77 I am using 1.7.6 and give me this error as well.

I have open atom with 3 perforce mappings inside. I don't know if this can cause problems.

**Comment by unional** [comment]
> I have open atom with 3 perforce mappings inside

Very likely. We currently only support one

**Comment by yordis** [comment]
@unional is there anyway to do this. Can you just give me some line for reference about this configuration and I can do something about it. 

Also the ability to add the P4 configuration like server, username and so on.

**Comment by unional** [comment]
Actually I am wrong. It should work.  Can you verify your error stack trace?

**Comment by olaekelund** [comment]
This issue started to appear on my computer for about a week ago. No changes has been made to the atom or perforce setup that should cause this.

[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.7.2
**System**: Microsoft Windows 10 Pro
**Thrown From**: [atom-perforce](https://github.com/mattsawyer77/atom-perforce) package, v1.7.6

### Stack Trace

Failed to activate the atom-perforce package

```
At Cannot read property 'split' of undefined

TypeError: Cannot read property 'split' of undefined
    at Object.setupEnvironment (C:\Users\ola.ekelund\.atom\packages\atom-perforce\lib\atom-perforce.js:147:40)
    at execP4Command (C:\Users\ola.ekelund\.atom\packages\atom-perforce\lib\atom-perforce.js:44:64)
    at Object.getChanges (C:\Users\ola.ekelund\.atom\packages\atom-perforce\lib\atom-perforce.js:458:13)
    at C:\Users\ola.ekelund\.atom\packages\atom-perforce\main.js:93:26
    at Workspace.module.exports.Workspace.observeTextEditors (C:\Users\ola.ekelund\AppData\Local\atom\app-1.7.2\resources\app.asar\src\workspace.js:307:9)
    at setupObservers (C:\Users\ola.ekelund\.atom\packages\atom-perforce\main.js:67:34)
    at Object.activate (C:\Users\ola.ekelund\.atom\packages\atom-perforce\main.js:185:17)
    at Package.module.exports.Package.activateNow (C:\Users\ola.ekelund\AppData\Local\atom\app-1.7.2\resources\app.asar\src\package.js:183:20)
    at C:\Users\ola.ekelund\AppData\Local\atom\app-1.7.2\resources\app.asar\src\package.js:156:32
    at Package.module.exports.Package.measure (C:\Users\ola.ekelund\AppData\Local\atom\app-1.7.2\resources\app.asar\src\package.js:92:15)
    at C:\Users\ola.ekelund\AppData\Local\atom\app-1.7.2\resources\app.asar\src\package.js:149:26
    at Package.module.exports.Package.activate (C:\Users\ola.ekelund\AppData\Local\atom\app-1.7.2\resources\app.asar\src\package.js:146:34)
    at PackageManager.module.exports.PackageManager.activatePackage (C:\Users\ola.ekelund\AppData\Local\atom\app-1.7.2\resources\app.asar\src\package-manager.js:538:21)
    at C:\Users\ola.ekelund\AppData\Local\atom\app-1.7.2\resources\app.asar\src\package-manager.js:519:29
    at Config.module.exports.Config.transactAsync (C:\Users\ola.ekelund\AppData\Local\atom\app-1.7.2\resources\app.asar\src\config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (C:\Users\ola.ekelund\AppData\Local\atom\app-1.7.2\resources\app.asar\src\package-manager.js:514:19)
    at PackageManager.module.exports.PackageManager.activate (C:\Users\ola.ekelund\AppData\Local\atom\app-1.7.2\resources\app.asar\src\package-manager.js:497:46)
    at C:\Users\ola.ekelund\AppData\Local\atom\app-1.7.2\resources\app.asar\src\atom-environment.js:754:28
```

### Commands

```
```

### Config

``` json
{
  "core": {
    "audioBeep": false,
    "autoHideMenuBar": true,
    "disabledPackages": [
      "wrap-guide",
      "welcome",
      "timecop",
      "styleguide",
      "spell-check",
      "release-notes",
      "package-generator",
      "metrics",
      "link",
      "language-yaml",
      "language-toml",
      "language-sql",
      "language-sass",
      "language-ruby-on-rails",
      "language-ruby",
      "language-perl",
      "language-objective-c",
      "language-mustache",
      "language-make",
      "language-java",
      "language-hyperlink",
      "language-go",
      "language-csharp",
      "language-clojure",
      "language-c",
      "image-view",
      "exception-reporting",
      "archive-view",
      "autoflow",
      "autosave",
      "background-tips",
      "language-python",
      "language-php",
      "language-property-list"
    ],
    "fileEncoding": "windows1252",
    "ignoredNames": [
      "*.r",
      ".*"
    ],
    "themes": [
      "atom-dark-ui",
      "one-dark-syntax"
    ]
  },
  "atom-perforce": {
    "autoEdit": true,
    "autoRevert": true
  }
}
```

### Installed Packages

``` coffee
# User
atom-perforce, v1.7.6
autocomplete-abl, v0.1.2
build, v0.60.0
color-picker, v2.1.1
file-icons, v1.7.7
fonts, v1.2.0
highlight-selected, v0.11.2
language-abl, v0.10.1
minimap, v4.22.1
minimap-highlight-selected, v4.4.0
minimap-selection, v4.4.0
Sublime-Style-Column-Selection, v1.5.1

# Dev
No dev packages
```

**Comment by unional** [comment]
This is the `Path` vs `PATH` issue in atom

**Comment by olaekelund** [comment]
What that issue about?

**Comment by yordis** [comment]
Just in case, could be that you can't find the Perforce configuration file?

I used Intellij and even there I configure the P4 connection per project.

**Comment by unional** [comment]
https://github.com/mattsawyer77/atom-perforce/issues/68

Please check out existing issues. Thanks. :tulip:

**Comment by olaekelund** [comment]
It was the Path issue. Thanks.

**Comment by mdouglass** [comment]
I am newly seeing this issue with atom-perforce 1.7.8 and Atom 1.11 as of this morning.

```
TypeError: Arguments to CompositeDisposable.add must have a .dispose() method
    at assertDisposable (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/composite-disposable.js:70:13)
    at CompositeDisposable.module.exports.CompositeDisposable.add (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/composite-disposable.js:43:11)
    at setupObservers (/Users/mdouglass/.atom/packages/atom-perforce/main.js:47:15)
    at Object.activate (/Users/mdouglass/.atom/packages/atom-perforce/main.js:185:17)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:183:20)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:156:32
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:149:26
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:146:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:538:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:460:29
    at exit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:73:16)
    at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:215:47)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:222:18
    at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:100:18)
    at emitOne (events.js:95:20)
    at Socket.emit (events.js:182:7)
    at Pipe._onclose (net.js:477:12)
```

**Comment by iancheng** [comment]
I am also seeing this issue upon updating to Atom 1.11.0. The "View Issue" button in the dialog links me here :)

Atom Version: 1.11.0
System: Mac OSX El Capitan 10.11.6
Thrown From: atom-perforce package, v1.7.8

```
TypeError: Arguments to CompositeDisposable.add must have a .dispose() method
    at assertDisposable (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/composite-disposable.js:70:13)
    at CompositeDisposable.module.exports.CompositeDisposable.add (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/composite-disposable.js:43:11)
    at setupObservers (/Users/ian/.atom/packages/atom-perforce/main.js:47:15)
    at Object.activate (/Users/ian/.atom/packages/atom-perforce/main.js:185:17)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:183:20)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:156:32
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:149:26
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:146:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:538:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:519:29
    at Config.module.exports.Config.transactAsync (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:514:19)
    at PackageManager.module.exports.PackageManager.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:497:46)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:779:28
```

**Comment by devilpig** [comment]
I also have this issue after updating to Atom 1.11.1
System: Windows 7
Thrown from: atom-perforce package, v1.7.8

`TypeError: Arguments to CompositeDisposable.add must have a .dispose() method
    at assertDisposable (C:\Users\fredriks\AppData\Local\atom\app-1.11.1\resources\app.asar\node_modules\event-kit\lib\composite-disposable.js:70:13)
    at CompositeDisposable.module.exports.CompositeDisposable.add (C:\Users\fredriks\AppData\Local\atom\app-1.11.1\resources\app.asar\node_modules\event-kit\lib\composite-disposable.js:43:11)
    at setupObservers (C:\Users\fredriks\.atom\packages\atom-perforce\main.js:47:15)
    at Object.activate (C:\Users\fredriks\.atom\packages\atom-perforce\main.js:185:17)
    at Package.module.exports.Package.activateNow (C:\Users\fredriks\AppData\Local\atom\app-1.11.1\resources\app.asar\src\package.js:183:20)
    at C:\Users\fredriks\AppData\Local\atom\app-1.11.1\resources\app.asar\src\package.js:156:32
    at Package.module.exports.Package.measure (C:\Users\fredriks\AppData\Local\atom\app-1.11.1\resources\app.asar\src\package.js:92:15)
    at C:\Users\fredriks\AppData\Local\atom\app-1.11.1\resources\app.asar\src\package.js:149:26
    at Package.module.exports.Package.activate (C:\Users\fredriks\AppData\Local\atom\app-1.11.1\resources\app.asar\src\package.js:146:34)
    at PackageManager.module.exports.PackageManager.activatePackage (C:\Users\fredriks\AppData\Local\atom\app-1.11.1\resources\app.asar\src\package-manager.js:538:21)
    at C:\Users\fredriks\AppData\Local\atom\app-1.11.1\resources\app.asar\src\package-manager.js:342:19
    at C:\Users\fredriks\AppData\Local\atom\app-1.11.1\resources\app.asar\src\config.js:635:20
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\fredriks\AppData\Local\atom\app-1.11.1\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (C:\Users\fredriks\AppData\Local\atom\app-1.11.1\resources\app.asar\node_modules\event-kit\lib\emitter.js:129:28)
    at Config.module.exports.Config.emitChangeEvent (C:\Users\fredriks\AppData\Local\atom\app-1.11.1\resources\app.asar\src\config.js:827:29)
    at Config.module.exports.Config.setRawValue (C:\Users\fredriks\AppData\Local\atom\app-1.11.1\resources\app.asar\src\config.js:612:19)
    at Config.module.exports.Config.set (C:\Users\fredriks\AppData\Local\atom\app-1.11.1\resources\app.asar\src\config.js:227:14)
    at Config.module.exports.Config.removeAtKeyPath (C:\Users\fredriks\AppData\Local\atom\app-1.11.1\resources\app.asar\src\config.js:377:12)
    at Package.module.exports.Package.enable (C:\Users\fredriks\AppData\Local\atom\app-1.11.1\resources\app.asar\src\package.js:77:26)
    at PackageManager.module.exports.PackageManager.enablePackage (C:\Users\fredriks\AppData\Local\atom\app-1.11.1\resources\app.asar\src\package-manager.js:169:14)
    at HTMLButtonElement.<anonymous> (C:\Users\fredriks\AppData\Local\atom\app-1.11.1\resources\app.asar\node_modules\settings-view\lib\package-card.js:343:27)
    at HTMLButtonElement.jQuery.event.dispatch (C:\Users\fredriks\AppData\Local\atom\app-1.11.1\resources\app.asar\node_modules\jquery\dist\jquery.js:4435:9)
    at HTMLButtonElement.elemData.handle (C:\Users\fredriks\AppData\Local\atom\app-1.11.1\resources\app.asar\node_modules\jquery\dist\jquery.js:4121:28)`

**Comment by mattsawyer77** [comment]
haven't looked deeply into this yet, but it could be an upstream bug: https://github.com/atom/atom/issues/12963

**Comment by saperio** [comment]
Hi, I add a pr to fix this: https://github.com/mattsawyer77/atom-perforce/pull/73
